#release configuration
#Thu Mar 19 17:59:54 CET 2026
projectVersionPolicyId=default
project.rel.org.jahia.se.modules\:contentBulkEdit=1.0.0
remoteTagging=true
project.scm.org.jahia.se.modules\:contentBulkEdit.developerConnection=scm\:git\:git@github.com\:smonier/contentBulkEdit.git
scm.commentPrefix=[skip ci] [maven-release-plugin]
project.scm.org.jahia.se.modules\:contentBulkEdit.connection=scm\:git\:git@github.com\:smonier/contentBulkEdit.git
completedPhase=end-release
scm.url=scm\:git\:git@github.com\:smonier/contentBulkEdit.git
project.scm.org.jahia.se.modules\:contentBulkEdit.tag=HEAD
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pushChanges=true
project.dev.org.jahia.se.modules\:contentBulkEdit=1.0.1-SNAPSHOT
project.scm.org.jahia.se.modules\:contentBulkEdit.url=https\://github.com/smonier/contentBulkEdit
scm.tag=contentBulkEdit-1.0.0
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean install
